package com.ayushsinghal.bhagavadgita.features.slok.domain.model.slok

data class SlokModel(
    val _id: String,
    val abhinav: AbhinavModel,
    val adi: AdiModel,
    val anand: AnandModel,
    val chapter: Int,
    val chinmay: ChinmayModel,
    val dhan: DhanModel,
    val gambir: GambirModel,
    val jaya: JayaModel,
    val madhav: MadhavModel,
    val ms: MsModel,
    val neel: NeelModel,
    val purohit: PurohitModel,
    val puru: PuruModel,
    val raman: RamanModel,
    val rams: RamsModel,
    val san: SanModel,
    val sankar: SankarModel,
    val siva: SivaModel,
    val slok: String,
    val srid: SridModel,
    val tej: TejModel,
    val transliteration: String,
    val vallabh: VallabhModel,
    val venkat: VenkatModel,
    val verse: Int
)